### PR TITLE
implement /stops

### LINKED ISSUE #1: List of stops in a bbox
Could another endpoint be added to fetch the stops in the configured bbox? That way, we’d be able to visualize the stops on a map, as well as snap it to OSM to calculate transfers between stops automatically.

An example of what we need: https://graph.irail.be/sncb/stops

`@id`, name, longitude and latitude would be great to be able to visualize the stop!

### PR DESCRIPTION
**Pull request by derhuerst**
closes #1

@pietercolpaert What do you think?

### CODE REVIEW

**Comment by derhuerst** [comment]
Tests are failing because there are no tests. 🙈

**Comment by pietercolpaert** [comment]
First sight of the code: looks great!

Give me a bit more time to test and check this though -- busy period :)

**Comment by pietercolpaert** [comment]
Approved changes: still some issues with it, but @hdelva will open a separate pull request for this!

Issues:
 - [ ] context is not complete: longitude, latitude and name need to be mapped to the right URIs
 - [ ] the URI parameter for departure time filtering is based on a timestamp. We expect an xsd:dateTime (ISO8601 subset). We agree this should’ve been better documented

**Comment by derhuerst** [comment]
> We expect an `xsd:dateTime` (ISO8601 subset).

AFAICT it doesn't *require* a timezone (offset) designator (just like ISO 8601). I'd like to make this required, as using local time (a.k.a. wall clock time) without tz information is ambiguous and problematic given that Linked Connections aims for federation of large public transportation networks.

**Pull request merged**
